/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-06-13 09:54:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WorkIn;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import java.util.List;
import com.study.mvc.model.javabean.StudentInfo;

public final class UserListJSON_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tdiv#main {\r\n");
      out.write("\t\twidth:800px;\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\ttop:300px;\r\n");
      out.write("\t\tleft: 50%;\r\n");
      out.write("\t\tmargin-left:-400px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable {\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv#main table {\r\n");
      out.write("\t\twidth: 800px;\r\n");
      out.write("\t\tborder: 2px solid blue;\r\n");
      out.write("\t\tborder-collapse: collapse;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttd {\r\n");
      out.write("\t\tborder: 1px solid blue;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../Myjs/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getStuInfo(forword){\r\n");
      out.write("\t\t$.post(\r\n");
      out.write("\t\t\t\"");
      out.print(request.getContextPath());
      out.write("/OracleOperationServlet\",\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\taction:\"seachByNameJSON\",\r\n");
      out.write("\t\t\t\tpageIndex: forword,\r\n");
      out.write("\t\t\t\tname:$(\"#stuName\").val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfunction(data){\r\n");
      out.write("\t\t\t\tvar students = eval(data);\r\n");
      out.write("\t\t\t\tvar htmlData = \"\";\r\n");
      out.write("\t\t\t\tvar student = \"\";\r\n");
      out.write("\t\t\t\tvar stuInfo = null;\r\n");
      out.write("\t\t\t\thtmlData +=\"<caption>学员信息一览</caption>\";\r\n");
      out.write("\t\t\t\thtmlData += \"<tr><td>序号</td><td>学号</td><td>姓名</td><td>性别</td><td>年龄</td><td>毕业院校</td><td colspan=\\\"2\\\">操作</td></tr>\"\r\n");
      out.write("\t\t\t\t$.each(students ,function(i){\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"<td>\" + students[i].id  +\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"<td>\" + students[i].num  +\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"<td>\" + students[i].name  +\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"<td>\" + students[i].age  +\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"<td>\" + students[i].sex  +\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"<td>\" + students[i].school  +\"</td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"<td><a href=\\\"");
      out.print(request.getContextPath() );
      out.write("/OracleOperationServlet?action=seachById&id=\"+ students[i].id +\"\\\">修改</a></td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"<td><a href=\\\"");
      out.print(request.getContextPath() );
      out.write("/OracleOperationServlet?action=del&delNum=\"+ students[i].id +\"\\\">删除</a></td>\";\r\n");
      out.write("\t\t\t\t\t\thtmlData += \"</tr>\";\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tif(students.length == 0){\r\n");
      out.write("\t\t\t\t\thtmlData += \"<tr >\";\r\n");
      out.write("\t\t\t\t\thtmlData += \"<td colspan=\\\"7\\\">没有获取到数据</td>\";\r\n");
      out.write("\t\t\t\t\thtmlData += \"</tr>\";\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\thtmlData +=  '<td colspan=\"2\"><input type=\"button\"  onclick=\"getStuInfo(\\'first\\')\" value=\"首页\" ></td>';\r\n");
      out.write("\t\t\t\t\thtmlData +=  '<td colspan=\"1\"><input type=\"button\"  onclick=\"getStuInfo(\\'pre\\')\" value=\"前页\" ></td>';\r\n");
      out.write("\t\t\t\t\thtmlData +=  '<td colspan=\"1\"><input type=\"button\"  onclick=\"getStuInfo(\\'next\\')\" value=\"次页\" ></td>';\r\n");
      out.write("\t\t\t\t\thtmlData +=  '<td colspan=\"2\"><input type=\"button\"  onclick=\"getStuInfo(\\'last\\')\" value=\"尾页\" ></td>';\r\n");
      out.write("\t\t\t\t\thtmlData +=  '<td colspan=\"2\"><input type=\"number\" id=\"pageIndex\">';\r\n");
      out.write("\t\t\t\t\thtmlData +=  '<input type=\"button\" onclick=\"getStuInfo($(\\'pageIndex\\').val())\" value=\"指定页\" ></td>';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#tb\").html(htmlData);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"JSON\"\r\n");
      out.write("\t\t)\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" \t$(function(){\r\n");
      out.write("\t\t$(\"#subB\").click(function(){\r\n");
      out.write("\t\t\tgetStuInfo('first');\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<div >\r\n");
      out.write("\t\t<form id=\"seachFm\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>姓名</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"stuName\" id=\"stuName\" ></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" style=\"text-align:center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"查找\" id=\"subB\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"重置\" onclick=\"seachFm.reset()\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\t\t<table id=\"tb\">\r\n");
      out.write("\t\t\t<caption>学员信息表</caption>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>序号</td>\r\n");
      out.write("\t\t\t\t<td>学号</td>\r\n");
      out.write("\t\t\t\t<td>姓名</td>\r\n");
      out.write("\t\t\t\t<td>性别</td>\r\n");
      out.write("\t\t\t\t<td>年龄</td>\r\n");
      out.write("\t\t\t\t<td>毕业院校</td>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">操作</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WorkIn/UserListJSON.jsp(131,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.stuList}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t");
          //  c:forEach
          org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
          _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
          // /WorkIn/UserListJSON.jsp(132,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fforEach_005f0.setVar("tmp");
          // /WorkIn/UserListJSON.jsp(132,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.stuList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          // /WorkIn/UserListJSON.jsp(132,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fforEach_005f0.setVarStatus("iid");
          int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
          try {
            int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
            if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              do {
                out.write("\r\n");
                out.write("\t\t\t\t\t<tr >\r\n");
                out.write("\t\t\t\t\t\t<td>");
                out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmp.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t<td>");
                out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmp.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t<td>");
                out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmp.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t<td>");
                out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmp.sex}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t<td>");
                out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmp.age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t<td>");
                out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmp.school}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                out.write("</td>\r\n");
                out.write("\t\t\t\t\t\t<td><a href=\"");
                out.print(request.getContextPath() );
                out.write("/OracleOperationServlet?action=seachById&id=");
                out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmp.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                out.write("\">修改</a></td>\r\n");
                out.write("\t\t\t\t\t\t<td><a href=\"");
                out.print(request.getContextPath() );
                out.write("/OracleOperationServlet?action=del&delNum=");
                out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tmp.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
                out.write("\">删除</a></td>\r\n");
                out.write("\t\t\t\t\t\t<td colspan=\"2\"><input type=\"button\"  onclick=\"getStuInfo('first')\" value=\"首页\" ></td>\r\n");
                out.write("\t\t\t\t\t\t<td colspan=\"1\"><input type=\"button\"  onclick=\"getStuInfo('pre')\" value=\"前页\" ></td>\r\n");
                out.write("\t\t\t\t\t\t<td colspan=\"1\"><input type=\"button\"  onclick=\"getStuInfo('next')\" value=\"次页\" ></td>\r\n");
                out.write("\t\t\t\t\t\t<td colspan=\"2\"><input type=\"button\"  onclick=\"getStuInfo('last')\" value=\"尾页\" ></td>\r\n");
                out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
                out.write("\t\t\t\t\t\t\t<input type=\"number\" id=\"pageIndex\">\r\n");
                out.write("\t\t\t\t\t\t\t<input type=\"button\" onclick=\"getStuInfo($('pageIndex').val())\" value=\"指定页\" >\r\n");
                out.write("\t\t\t\t\t\t</td>\r\n");
                out.write("\t\t\t\t\t</tr>\r\n");
                out.write("\t\t\t\t");
                int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
                if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                  break;
              } while (true);
            }
            if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              return;
            }
          } catch (java.lang.Throwable _jspx_exception) {
            while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
              out = _jspx_page_context.popBody();
            _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
          } finally {
            _jspx_th_c_005fforEach_005f0.doFinally();
            _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
          }
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WorkIn/UserListJSON.jsp(126,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.stuList}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t<tr id=\"dataCg\">\r\n");
        out.write("\t\t\t\t\t<td colspan=\"7\">没有获取到信息</td>\r\n");
        out.write("\t\t\t\t</tr>\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
