/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-05-18 00:58:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.work;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class A1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar ls = {};\r\n");
      out.write("\tls.errInfo = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\tls.$ = function(id){\r\n");
      out.write("\t\treturn document.getElementById(id);\r\n");
      out.write("\t}\r\n");
      out.write("\tls.init = function(){\r\n");
      out.write("\t\tls.$(\"checkUser\").style.display = none;\r\n");
      out.write("\t\tls.$(\"checkPwd\").style.display = none;\r\n");
      out.write("\t\tls.$(\"errInfo\").style.display = none;\r\n");
      out.write("\t}\r\n");
      out.write("\tls.checkData = function(element, checkElement, errInfoElement, inputText){\r\n");
      out.write("\t\tvar rec = true;\r\n");
      out.write("\t\tif(element.value==null || element.value==\"\"){\r\n");
      out.write("\t\t\tcheckElement.style.display = \"inline\";\r\n");
      out.write("\t\t\terrInfoElement.style.display = \"block\";\r\n");
      out.write("\t\t\tls.errInfo += inputText + \"不可以为空\";\r\n");
      out.write("\t\t\trec = false;\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn rec;\r\n");
      out.write("\t}\r\n");
      out.write("\tls.checkAllData = function(){\r\n");
      out.write("\t\tvar rec = true;\r\n");
      out.write("\t\tls.errInfo = \"\";\r\n");
      out.write("\t\tif(!ls.checkData(ls.$(\"user\"), ls.$(\"checkUser\"), ls.$(\"errInfo\"), \"用户名\")\r\n");
      out.write("\t\t\t| !ls.checkData(ls.$(\"pwd\"), ls.$(\"checkPwd\"), ls.$(\"errInfo\"), \"密码\")){\r\n");
      out.write("\t\t\trec = false;\r\n");
      out.write("\t\t\tls.$(\"errInfo\").innerText = ls.errInfo;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn rec;\r\n");
      out.write("\t}\r\n");
      out.write("\tls.sendRequest = function(){\r\n");
      out.write("\t\tif(!ls.checkAllData()){\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t/* 总结：当是a标签的时候与是否有返回值无关，至于是否定义location.href有关 */\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\tvar user = ls.$(\"user\").value;\r\n");
      out.write("\t\t\tvar pwd = ls.$(\"pwd\").value;\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.print(request.getContextPath() );
      out.write("/AS1\";\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* a标签方式只能通过get超级连接方式传值否则值不可传递 */\r\n");
      out.write("\tls.sendRequestA = function(){\r\n");
      out.write("\t\tif(!ls.checkAllData()){\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t/* 总结：当是a标签的时候与是否有返回值无关，与是否定义location.href有关 */\r\n");
      out.write("\t\t\t/* 如果是href赋值方式跳转 \r\n");
      out.write("\t\t\t\t1. 无return 一直会跳转\r\n");
      out.write("\t\t\t\t2. 有return return false不跳转， return true跳转\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\tvar user = ls.$(\"user\").value;\r\n");
      out.write("\t\t\tvar pwd = ls.$(\"pwd\").value;\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\tdocument.getElementById(\"ar\").href = \"");
      out.print(request.getContextPath() );
      out.write("/AS1?user=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ user + \"&pwd=\" + pwd;\r\n");
      out.write("\t\t\tdocument.getElementById(\"a\").href = \"");
      out.print(request.getContextPath() );
      out.write("/AS1?user=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ user + \"&pwd=\" + pwd;\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tls.sendRequestB = function(){\r\n");
      out.write("\t\t/*button标签的与renturn有关  */\r\n");
      out.write("\t\tif(!ls.checkAllData()){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\tvar user = ls.$(\"user\").value;\r\n");
      out.write("\t\t\tvar pwd = ls.$(\"pwd\").value;\r\n");
      out.write("\t\t\tdocument.forms[\"myFM\"].action = \"");
      out.print(request.getContextPath() );
      out.write("/AS1\";\r\n");
      out.write("\t\t\tdocument.forms[\"myFM\"].submit();\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"myFM\" action=\"");
      out.print(request.getContextPath() );
      out.write("/AS1\" method=\"get\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<span>用户名：</span>\r\n");
      out.write("\t\t<input type=\"text\" name=\"user\"  id=\"user\" /> \r\n");
      out.write("\t\t<span id=\"checkUser\" style=\"color:red;display:none\">*</span>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<span>密码：</span>\r\n");
      out.write("\t\t<input type=\"password\" name=\"pwd\" id=\"pwd\" /> \r\n");
      out.write("\t\t<span id=\"checkPwd\" style=\"color:red;display:none\">*</span>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"提交\" />\r\n");
      out.write("\t\t<input type=\"reset\" value=\"重置\" />\r\n");
      out.write("\t\t<a id=\"ar\"  onclick=\"return ls.sendRequestA()\">超级链接提交return</a>\r\n");
      out.write("\t\t<a id=\"a\"  onclick=\"ls.sendRequestA()\">超级链接提交</a>\r\n");
      out.write("\t\t<button onclick=\"return ls.sendRequestB()\"> 按钮提交return </button>\r\n");
      out.write("\t\t<button onclick=\"ls.sendRequestB()\"> 按钮提交</button>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<p id=\"errInfo\" style=\"color:red;display:none\"></p>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
