/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-05-21 10:27:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.workIn;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction getCookie (){\r\n");
      out.write("\t\t");
 
			Cookie [] ck = request.getCookies();
			String user = null;
			String pwd = null;
			String errInfo = null;
			for (Cookie c: ck) {
				if(c.getName().equals("user")){
					user = c.getValue();
					System.out.println(user);
					System.out.println("cookie用户名 :" +new String(user.getBytes("ISO-8859-1"), "UTF-8"));
				}
				if(c.getName().equals("pwd")){
					pwd = c.getValue();
					System.out.println("cookiepwd:" +pwd);
				}
				if(c.getName().equals("errInfo")){
					errInfo = c.getValue();
					System.out.println("cookie错误信息 :" +errInfo);
				}
			}
			if(user!=null || (user!=null&& !user.equals(""))){
				
				if(pwd!=null || (pwd!=null&& !pwd.equals(""))){
					/* out.write("<script type='text/javascript'>document.getElementById('user').value =" 
							+ user +";document.getElementById('pwd').value =" 
							+ pwd + ";document.getElementById('errInfo').innerText="
							+ errInfo
							+ ";document.getElementById('errInfo').style.display = 'inline';</script>"); */
					out.write("document.getElementById('user').value ='" 
							+ user +"'");
					System.out.println("进入。。。。。。");
				}else {
					out.write("function errInfoAdd(){document.getElementById('errInfo').innerText='"
							+ errInfo
							+ "';document.getElementById('errInfo').style.display = 'inline';}");
				}
			}
			/* else {
				out.write("function errInfoAdd(){document.getElementById('errInfo').innerText='"
						+ errInfo
						+ "';document.getElementById('errInfo').style.display = 'inline';}");
			} */
		
      out.write(" \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<body onload=\"getCookie()\">\r\n");
      out.write("\t<div id=\"errInfo\"></div>\r\n");
      out.write("\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/MyServlet\" method=\"get\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>用户名：</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"user\" id=\"user\" />\r\n");
      out.write("\t\t\t\t\t<span id=\"checkUser\" style=\"color:red; display:none\">*</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>密码：</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"pwd\" id=\"pwd\" />\r\n");
      out.write("\t\t\t\t\t<span id=\"checkPwd\" style=\"color:red; display:none\">*</span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"提交\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"reset\" value=\"重置\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
