/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-06-08 12:33:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class accessSafeAnswer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>密码找回</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<script src=\"js/cookie.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("\t<script type=\"application/javascript\">\r\n");
      out.write("\t\tvar ls = {};\r\n");
      out.write("\t\tvar nameIsOk = false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tls.$ = function(id){\r\n");
      out.write("\t\t\treturn document.getElementById(id);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tls.checkData = function(elmt){\r\n");
      out.write("\t\t\tvar ret = true;\r\n");
      out.write("\t\t\tif(elmt.value == null || elmt.value==\"\"){\r\n");
      out.write("\t\t\t\tret = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn ret;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tls.initCheckInfo = function(errElmt){\r\n");
      out.write("\t\t\tconsole.log(\"focus in\");\r\n");
      out.write("\t\t\terrElmt.innerText = \"*\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tls.checkDataAddErr = function(elmt, inputName , errElmt){\r\n");
      out.write("\t\t\tvar ret = true;\r\n");
      out.write("\t\t\tif(!ls.checkData(elmt)){\r\n");
      out.write("\t\t\t\terrElmt.innerText = inputName + \"不能为空\";\r\n");
      out.write("\t\t\t\tret = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn ret;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tls.checkAllData = function(){\r\n");
      out.write("\t\t\tvar ret = true;\r\n");
      out.write("\t\t\tif(!nameIsOk|\r\n");
      out.write("\t\t\t\t!ls.checkDataAddErr(ls.$('answer1'), '答案', ls.$('answer1CheckInfo'))|\r\n");
      out.write("\t\t\t\t!ls.checkDataAddErr(ls.$('answer2'), '答案', ls.$('answer2CheckInfo'))|\r\n");
      out.write("\t\t\t\t!ls.checkDataAddErr(ls.$('answer3'), '答案', ls.$('answer3CheckInfo'))\r\n");
      out.write("\t\t\t){\r\n");
      out.write("\t\t\t\tret = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn ret;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tls.getEECIdCookie = function(){\r\n");
      out.write("\t\t\tvar eecIdCK = getCookie(\"eecId\");\r\n");
      out.write("\t\t\tif(eecIdCK!=null&&eecIdCK!=\"\"){\r\n");
      out.write("\t\t\t\tls.$(\"eecId\").value=eecIdCK;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tls.nameCheck = function(){\r\n");
      out.write("\t\t\tvar nameElmt = ls.$(\"eecId\");\r\n");
      out.write("\t\t\tnameIsOk = false;\r\n");
      out.write("\t\t\tif(!ls.checkDataAddErr(nameElmt, \"学号\",  ls.$(\"eecIdCheckInfo\"))){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tnameIsOk = true;\r\n");
      out.write("\t\t\tls.$(\"eecIdCheckInfo\").innerText = \"用户名正确\";\r\n");
      out.write("\t\t\tls.$(\"eecIdCheckInfo\").style.color = \"green\";\r\n");
      out.write("\t\t\t/*var xmlHttp;\r\n");
      out.write("\t\t\tif(Window.ActiveXObject){\r\n");
      out.write("\t\t\t\txmlHttp = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\txmlHttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\txmlHttp.onreadystatechange = function(){\r\n");
      out.write("\t\t\t\tif(xmlHttp.readyState==4 && xmlHttp.status==200){\r\n");
      out.write("\t\t\t\t\tif(xmlHttp.responseText == \"false\"){\r\n");
      out.write("\t\t\t\t\t\tnameIsOk = false;\r\n");
      out.write("\t\t\t\t\t\tls.$(\"eecIdCheckInfo\").innerText = \"用户名不存在\";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tnameIsOk = true;\r\n");
      out.write("\t\t\t\t\t\tls.$(\"eecIdCheckInfo\").innerText = \"用户名正确\";\r\n");
      out.write("\t\t\t\t\t\tls.$(\"eecIdCheckInfo\").style.color = \"green\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\txmlHttp.open(\"myServlet?name=\" + name);\r\n");
      out.write("\t\t\txmlHttp.send();*/\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tls.submitForm = function(){\r\n");
      out.write("\t\t\tif(!ls.checkAllData()){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//document.forms[\"getAnsewerForm\"].action = \"https://www.baidu.com\";\r\n");
      out.write("\t\t\t//document.Submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<body  onload=\"ls.getEECIdCookie()\">\r\n");
      out.write("\t\t<form id=\"getAnsewerForm\" action=\"AccessSafeAnswerServlet\" method=\"post\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p>学号</p>\r\n");
      out.write("\t\t\t\t<input  type=\"text\" name=\"eecId\" id=\"eecId\" \r\n");
      out.write("\t\t\t\t\tonfocusin=\"ls.initCheckInfo(ls.$('eecIdCheckInfo'))\"\r\n");
      out.write("\t\t\t\t\tonfocusout=\"ls.nameCheck()\" autocomplete=\"on\"  />\r\n");
      out.write("\t\t\t\t<span id=\"eecIdCheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p style=\"font-size: large; font-weight: 800;\">安全回答</p>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<p>你的家乡在哪里？</p>\r\n");
      out.write("\t\t\t\t<input  type=\"text\" name=\"answer1\" id=\"answer1\"\r\n");
      out.write("\t\t\t\t\tonfocusin=\"ls.initCheckInfo(ls.$('answer1CheckInfo'))\"\r\n");
      out.write("\t\t\t\t\tonfocusout=\"ls.checkDataAddErr(ls.$('answer1'), '答案', ls.$('answer1CheckInfo'))\" />\r\n");
      out.write("\t\t\t\t<span name=\"answer1CheckInfo\" id=\"answer1CheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p>你的班主任姓名？</p>\r\n");
      out.write("\t\t\t\t\t<input  type=\"text\" name=\"answer2\" id=\"answer2\"\r\n");
      out.write("\t\t\t\t\tonfocusin=\"ls.initCheckInfo(ls.$('answer2CheckInfo'))\"\r\n");
      out.write("\t\t\t\t\tonfocusout=\"ls.checkDataAddErr(ls.$('answer2'), '答案', ls.$('answer2CheckInfo'))\" />\r\n");
      out.write("\t\t\t\t<span name=\"answer2CheckInfo\" id=\"answer2CheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p>你喜欢什么运动？</p>\r\n");
      out.write("\t\t\t\t\t<input  type=\"text\" name=\"answer3\" id=\"answer3\"\r\n");
      out.write("\t\t\t\t\tonfocusin=\"ls.initCheckInfo(ls.$('answer3CheckInfo'))\"\r\n");
      out.write("\t\t\t\t\tonfocusout=\"ls.checkDataAddErr(ls.$('answer3'), '答案', ls.$('answer3CheckInfo'))\" />\r\n");
      out.write("\t\t\t\t<span name=\"answer3CheckInfo\" id=\"answer3CheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input type=\"submit\" onclick=\"return ls.submitForm()\"  />\r\n");
      out.write("\t\t\t\t<input type=\"reset\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
