/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-06-14 22:48:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddTeacher_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tdiv{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\twidth:400px;\r\n");
      out.write("\t\tleft:50%;\r\n");
      out.write("\t\ttop:20%;\r\n");
      out.write("\t\tmargin-left:-200px;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable{\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t\twidth:400px;\r\n");
      out.write("\t\tborder:2px solid blue;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd{\r\n");
      out.write("\t\tborder: 1px solid blue;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("\tfunction initCheckInfo(errInfoId){\r\n");
      out.write("\t\t$(errInfoId).text(\"*\");\r\n");
      out.write("\t}\r\n");
      out.write("\t// 关于性别的判断数据库需要去对性别设计固定值\r\n");
      out.write("\tfunction checkDataAddErr(id, errInfoId){\r\n");
      out.write("\t\tvar value = $(id).val();\r\n");
      out.write("\t\tconsole.log(id + \" 值为 \" + value);\r\n");
      out.write("\t\tif(value == null || value==\"\"){\r\n");
      out.write("\t\t\t$(errInfoId).text(\"不可以为空\");\r\n");
      out.write("\t\t\treturn false; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(id==\"#classId\" || id==\"#eecId\" || id==\"#eecName\" || id==\"#age\" || id==\"#roleId\"){\r\n");
      out.write("\t\t\t//console.log(typeof(parseInt(value)));\r\n");
      out.write("\t\t\t// TODO 格式判断 关系运算符\r\n");
      out.write("\t\t\t/* if(typeof(parseInt(value)) === \"number\"){\r\n");
      out.write("\t\t\t\t$(errInfoId).text(\"格式有误\");\r\n");
      out.write("\t\t\t\treturn false; \r\n");
      out.write("\t\t\t} */\r\n");
      out.write("\t\t\tvar reg = new RegExp(\"^[0-9]*$\");\r\n");
      out.write("\t\t    if(!reg.test(value)){\r\n");
      out.write("\t\t    \t$(errInfoId).text(\"格式有误\");\r\n");
      out.write("\t\t    \treturn;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(id==\"#email\"){\r\n");
      out.write("\t\t\tvar myreg = /^([a-zA-Z0-9]+[_|\\_|\\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\\_|\\.]?)*[a-zA-Z0-9]+\\.[a-zA-Z]{2,3}$/;\r\n");
      out.write("\t\t\tif(!myreg.test(value))\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$(errInfoId).text(\"请输入有效的E_mail！\");\r\n");
      out.write("\t\t\t    return false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(id==\"#telephone\"){\r\n");
      out.write("\t\t\tvar myreg = /^(((13[0-9]{1})|(15[0-9]{1})|(18[0-9]{1}))+\\d{8})$/; \r\n");
      out.write("\t\t\tif(!myreg.test(value)) \r\n");
      out.write("\t\t\t{ \r\n");
      out.write("\t\t\t\t$(errInfoId).text(\"请输入有效的手机号码！\");\r\n");
      out.write("\t\t\t    return false; \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction getEecUserInfo(forward){\r\n");
      out.write("\t\tshowInfo();\r\n");
      out.write("\t\t$.post(\r\n");
      out.write("\t\t\t\t\"");
      out.print(request.getContextPath());
      out.write("/AdminServlet\",\t\t\t\t\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\taction:forward,\r\n");
      out.write("\t\t\t\t\tclassId:$(\"#classId\").val(),\r\n");
      out.write("\t\t\t\t\teecId:$(\"#eecId\").val(),\r\n");
      out.write("\t\t\t\t\teecName:$(\"#eecName\").val(),\r\n");
      out.write("\t\t\t\t\tsex:$(\"#sex\").val(),\r\n");
      out.write("\t\t\t\t\tage:$(\"#age\").val(),\r\n");
      out.write("\t\t\t\t\temail:$(\"#email\").val(),\r\n");
      out.write("\t\t\t\t\ttelephone:$(\"#telephone\").val(),\r\n");
      out.write("\t\t\t\t\troleId:$(\"#roleId\").val()\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tfunction(data){\r\n");
      out.write("\t\t\t\t\t//console.log(\"数据解析支持成功\");\r\n");
      out.write("\t\t\t\t\tvar eecUsers = eval(data);\r\n");
      out.write("\t\t\t\t\tvar result = \"\";\r\n");
      out.write("\t\t\t\t\tif(eecUsers == null){\r\n");
      out.write("\t\t\t\t\t\tresult = \"没有获取到数据\";\r\n");
      out.write("\t\t\t\t\t}else if(eecUsers.error!=null){\r\n");
      out.write("\t\t\t\t\t\tresult = eecUsers.error;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tlocation.href = \"Admin.jsp\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#msg\").text(result);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"JSON\"\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#subB\").click(function(){\r\n");
      out.write("\t\t\tgetEecUserInfo(\"insertData\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<form id=\"regFM\" action=\"");
      out.print(request.getContextPath() );
      out.write("/AdminServlet?action=insertData\" method=\"post\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<!--TODO 做成下拉框  -->\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>班级</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"classId\" id=\"eecId\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusin=\"initCheckInfo('#classIdCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusout=\"checkDataAddErr('#classId', '#classIdCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t\t<span name=\"classIdCheckInfo\" id=\"classIdCheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>学号</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"eecId\"  id=\"eecId\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusin=\"initCheckInfo('#eecIdCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusout=\"checkDataAddErr('#eecId', '#eecIdCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t\t<span name=\"eecIdCheckInfo\" id=\"eecIdCheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>姓名</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"eecName\"  id=\"eecName\" \r\n");
      out.write("\t\t\t\t\t\t\tonfocusin=\"initCheckInfo('#eecNameCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusout=\"checkDataAddErr('#eecName', '#eecNameCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t\t<span name=\"eecNameCheckInfo\" id=\"eecNameCheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>性别</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t男<input type=\"radio\" name=\"sex\" value=\"男\" />\r\n");
      out.write("\t\t\t\t\t\t女<input type=\"radio\" name=\"sex\" value=\"女\" />\r\n");
      out.write("\t\t\t\t\t\t<span name=\"sexCheckInfo\" id=\"sexCheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>年龄</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"age\"  id=\"age\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusin=\"initCheckInfo('#ageCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusout=\"checkDataAddErr('#age', '#ageCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t\t<span name=\"ageCheckInfo\" id=\"ageCheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>邮箱</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"email\"   id=\"email\"  \r\n");
      out.write("\t\t\t\t\t\t\tonfocusin=\"initCheckInfo('#emailCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusout=\"checkDataAddErr('#email', '#emailCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t\t<span name=\"emailCheckInfo\" id=\"emailCheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>手机号</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"telephone\" id=\"telephone\" \r\n");
      out.write("\t\t\t\t\t\t\tonfocusin=\"initCheckInfo('#telephoneCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusout=\"checkDataAddErr('#telephone', '#telephoneCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t />\r\n");
      out.write("\t\t\t\t\t\t<span name=\"telephoneCheckInfo\" id=\"telephoneCheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>职务</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"roleName\" id=\"roleName\" \r\n");
      out.write("\t\t\t\t\t\t\tonfocusin=\"initCheckInfo('#roleNameCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t\tonfocusout=\"checkDataAddErr('#roleName', '#roleNameCheckInfo')\"\r\n");
      out.write("\t\t\t\t\t\t />\r\n");
      out.write("\t\t\t\t\t\t<span name=\"roleNameCheckInfo\" id=\"roleNameCheckInfo\" style=\"color:red\">*</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"添加数据\"  id=\"subB\" >\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"重置数据\" onclick=\"regFM.reset()\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"msg\"></div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
