/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-06-09 02:49:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class msg03_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/msgOne1.jsp", Long.valueOf(1496976563703L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>留言板</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar msgList = [\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ttitle:'111',\r\n");
      out.write("\t\t\t\theadImg: 'img/1.jpg',\r\n");
      out.write("\t\t\t\tname:'小明',\r\n");
      out.write("\t\t\t\tcontent:'我是留言1',\r\n");
      out.write("\t\t\t\ttime: '2017-06-07 8:00'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ttitle:'111',\r\n");
      out.write("\t\t\t\tname:'小红',\r\n");
      out.write("\t\t\t\theadImg: 'img/2.jpg',\r\n");
      out.write("\t\t\t\tcontent:'我是留言2',\r\n");
      out.write("\t\t\t\ttime: '2017-06-07 8:11'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ttitle:'111',\r\n");
      out.write("\t\t\t\tname:'小强',\r\n");
      out.write("\t\t\t\theadImg: 'img/3.jpg',\r\n");
      out.write("\t\t\t\tcontent:'我是留言2',\r\n");
      out.write("\t\t\t\ttime: '2017-06-07 8:22'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ttitle:'111',\r\n");
      out.write("\t\t\t\tname:'小芳',\r\n");
      out.write("\t\t\t\theadImg: 'img/4.jpg',\r\n");
      out.write("\t\t\t\tcontent:'我是留言3',\r\n");
      out.write("\t\t\t\ttime: '2017-06-07 8:33'\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t]\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar ls = {};\r\n");
      out.write("\t\tls.$ = function(id){\r\n");
      out.write("\t\t\treturn document.getElementById(id);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tls.forLength = msgList.length>10?10:msgList.length;\r\n");
      out.write("\t\tls.initImgInfo = function(){\r\n");
      out.write("\t\t\tvar imgId = \"\";\r\n");
      out.write("\t\t\tfor(var i=1; i<=ls.forLength;i++){\r\n");
      out.write("\t\t\t\timgId = \"img_0\" + i;\r\n");
      out.write("\t\t\t\tif(i>9){\r\n");
      out.write("\t\t\t\t\timgId = \"img_\" + i;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tconsole.log(imgId);\r\n");
      out.write("\t\t\t\tif(ls.$(imgId)==null || ls.$(imgId) == \"\"){\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tls.$(imgId).src = msgList[i-1].headImg;\r\n");
      out.write("\t\t\t\tconsole.log(ls.$(imgId).src);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tls.initNameInfo = function(){\r\n");
      out.write("\t\t\tvar nameId = \"\";\r\n");
      out.write("\t\t\tfor(var i=1; i<=ls.forLength;i++){\r\n");
      out.write("\t\t\t\tnameId = \"name_0\" + i;\r\n");
      out.write("\t\t\t\tif(i>9){\r\n");
      out.write("\t\t\t\t\tnameId = \"name_\" + i;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(ls.$(nameId)==null || ls.$(nameId) == \"\"){\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tls.$(nameId).innerText = msgList[i-1].name;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tls.initFloorInfo = function(){\r\n");
      out.write("\t\t\tvar floorId = \"\";\r\n");
      out.write("\t\t\tfor(var i=1; i<=ls.forLength;i++){\r\n");
      out.write("\t\t\t\tfloorId = \"floor_0\" + i;\r\n");
      out.write("\t\t\t\tif(i>9){\r\n");
      out.write("\t\t\t\t\tfloorId = \"floor_\" + i;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(ls.$(floorId)==null || ls.$(floorId) == \"\"){\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tls.$(floorId).innerText = '第'+i+'楼';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tls.initContentInfo = function(){\r\n");
      out.write("\t\t\tvar contentId = \"\";\r\n");
      out.write("\t\t\tfor(var i=1; i<=ls.forLength;i++){\r\n");
      out.write("\t\t\t\tcontentId = \"content_0\" + i;\r\n");
      out.write("\t\t\t\tif(i>9){\r\n");
      out.write("\t\t\t\t\tcontentId = \"content_\" + i;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(ls.$(contentId)==null || ls.$(contentId) == \"\"){\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tls.$(contentId).innerText = msgList[i-1].content;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tls.initTimeInfo = function(){\r\n");
      out.write("\t\t\tvar timeId = \"\";\r\n");
      out.write("\t\t\tfor(var i=1; i<=ls.forLength;i++){\r\n");
      out.write("\t\t\t\ttimeId = \"time_0\" + i;\r\n");
      out.write("\t\t\t\tif(i>9){\r\n");
      out.write("\t\t\t\t\ttimeId = \"time_\" + i;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(ls.$(timeId)==null || ls.$(timeId) == \"\"){\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tls.$(timeId).innerText = msgList[i-1].time;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tls.initInfo = function(){\r\n");
      out.write("\t\t\tls.initImgInfo();\r\n");
      out.write("\t\t\tls.initNameInfo();\r\n");
      out.write("\t\t\tls.initFloorInfo();\r\n");
      out.write("\t\t\tls.initContentInfo();\r\n");
      out.write("\t\t\tls.initTimeInfo();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction testShow(elmt){\r\n");
      out.write("\t\t\telmt.style.display=\"block\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction testHide(elmt){\r\n");
      out.write("\t\t\telmt.style.display=\"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction showAllMsg(){\r\n");
      out.write("\t\t\tfor(var i=0; i<msgList.length;i++){\r\n");
      out.write("\t\t\t\tconsole.log(\"name为:\" + msgList[i].name);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction deltInfo(id){\r\n");
      out.write("\t\t\tvar num =  id.indexOf('msgMain_');\r\n");
      out.write("\t\t\tconsole.log(\"num为\" + num);\r\n");
      out.write("\t\t\tif(num!=-1){\r\n");
      out.write("\t\t\t\tvar msgIndex = parseInt(id.substring(num+'msgMain_'.length, id.length));\r\n");
      out.write("\t\t\t\tconsole.log(\"msg index 为\" + msgIndex);\r\n");
      out.write("\t\t\t\tif(msgList[msgIndex-1]){\r\n");
      out.write("\t\t\t\t\t//msgList.splice(msgIndex,1);\r\n");
      out.write("\t\t\t\t\tmsgList[msgIndex-1] = null;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//showAllMsg();\r\n");
      out.write("\t\t\t\tls.$(id).style.display=\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction changeContent(sourceContentId, editeDivId, editeContentId){\r\n");
      out.write("\t\t\tvar value = ls.$(sourceContentId).innerText;\r\n");
      out.write("\t\t\tls.$(editeContentId).value = value;\r\n");
      out.write("\t\t\tls.$(editeDivId).style.display = 'block';\r\n");
      out.write("\t\t\tls.$(sourceContentId).style.display = 'none';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction submitValue(sourceContentId, editeDivId, editeContentId){\r\n");
      out.write("\t\t\tvar value = ls.$(editeContentId).value;\r\n");
      out.write("\t\t\tls.$(sourceContentId).innerText = value;\r\n");
      out.write("\t\t\tls.$(sourceContentId).style.display = 'block';\r\n");
      out.write("\t\t\tls.$(editeDivId).style.display = 'none';\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/content.css\"/>\r\n");
      out.write("\t<body onload=\"ls.initInfo()\">\r\n");
      out.write("\t\t<div id=\"show\">\r\n");
      out.write("\t\t\t<!-- <div class=\"c1\" id=\"msgMain_01\">\r\n");
      out.write("\t\t\t\t<hr style=\"width: 1000px; height: 1px; background-color: grey; border:0px\">\r\n");
      out.write("\t\t\t\t<div class=\"imgd\">\r\n");
      out.write("\t\t\t\t\t<img id=\"img_01\" alt=\"headImg\" width=\"100px\" height=\"100px\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"name\" id=\"name_01\"></span>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<span class=\"time\" id=\"floor_01\" ></span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t<ul style=\"list-style-type: none; \">\r\n");
      out.write("\t\t\t\t\t\t\t<li  onmouseleave=\"testHide(ls.$('hide_01'))\" onmouseover=\"testShow(ls.$('hide_01'))\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"\" >▼</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"hide\" id=\"hide_01\" style=\"display: none;text-align:center;list-style-type: none; margin-left: -60px;border: 1px solid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a  onclick=\"return deltInfo('msgMain_01')\">删除</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a  onclick=\"return changeContent('content_01', 'editeDiv_01', 'editContent_01')\">更改</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"edit\" id=\"editeDiv_01\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"editContent_01\" name=\"\" rows=\"10\" cols=\"75\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"确认\"  onclick=\"return submitValue('content_01', 'editeDiv_01', 'editContent_01')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"reset\" value=\"取消\" />\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"innerContern\" id=\"content_01\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"time\" id=\"time_01\"></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction initImgId(){\r\n");
      out.write("\t\tdocument.getElementsByTagName(\"img\").id = \"img_02\";\r\n");
      out.write("\t\t//console.log(\"img 的图片\" + document.getElementById(\"img_02\").scr);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body onload=\"initImgId()\">\r\n");
      out.write("\t<div class=\"c1\" id=\"msgMain_01\">\r\n");
      out.write("\t\t<hr style=\"width: 1000px; height: 1px; background-color: grey; border:0px\">\r\n");
      out.write("\t\t<div class=\"imgd\">\r\n");
      out.write("\t\t\t<img id=\"img_01\" alt=\"headImg\" width=\"100px\" height=\"100px\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span class=\"name\" id=\"name_01\"></span>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<span class=\"time\" id=\"floor_01\" ></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t<ul style=\"list-style-type: none; \">\r\n");
      out.write("\t\t\t\t\t<li  onmouseleave=\"testHide(ls.$('hide_01'))\" onmouseover=\"testShow(ls.$('hide_01'))\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" >▼</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"hide\" id=\"hide_01\" style=\"display: none;text-align:center;list-style-type: none; margin-left: -60px;border: 1px solid;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a  onclick=\"return deltInfo('msgMain_01')\">删除</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a  onclick=\"return changeContent('content_01', 'editeDiv_01', 'editContent_01')\">更改</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"edit\" id=\"editeDiv_01\">\r\n");
      out.write("\t\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<textarea id=\"editContent_01\" name=\"\" rows=\"10\" cols=\"75\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"确认\"  onclick=\"return submitValue('content_01', 'editeDiv_01', 'editContent_01')\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" value=\"取消\" />\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"innerContern\" id=\"content_01\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p class=\"time\" id=\"time_01\"></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"c1\" id=\"msgMain_10\">\r\n");
      out.write("\t\t\t\t<hr style=\"width: 1000px; height: 1px; background-color: grey; border:0px\">\r\n");
      out.write("\t\t\t\t<div class=\"imgd\">\r\n");
      out.write("\t\t\t\t\t<img id=\"img_10\" alt=\"headImg\" width=\"100px\" height=\"100px\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"name\" id=\"name_10\"></span>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<span class=\"time\" id=\"floor_10\" ></span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t\t\t<ul style=\"list-style-type: none; \">\r\n");
      out.write("\t\t\t\t\t\t\t<li  onmouseleave=\"testHide(ls.$('hide_10'))\" onmouseover=\"testShow(ls.$('hide_10'))\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"\" >▼</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul  class=\"hide\" id=\"hide_10\" style=\"display: none;text-align:center;list-style-type: none; margin-left: -60px;border: 1px solid;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a  onclick=\"return deltInfo('msgMain_10')\">删除</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a  onclick=\"return changeContent('content_10', 'editeDiv_10', 'editContent_10')\">更改</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"edit\" id=\"editeDiv_10\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"editContent_10\" name=\"\" rows=\"10\" cols=\"75\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"确认\"  onclick=\"return submitValue('content_10', 'editeDiv_10', 'editContent_10')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"reset\" value=\"取消\" />\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"innerContern\" id=\"content_10\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p class=\"time\" id=\"time_10\"></p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr style=\"width: 1000px; height: 3px; background-color: gainsboro; border:0px\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
