/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-06-09 02:49:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class msgOne1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction initImgId(){\r\n");
      out.write("\t\tdocument.getElementsByTagName(\"img\").id = \"img_02\";\r\n");
      out.write("\t\t//console.log(\"img 的图片\" + document.getElementById(\"img_02\").scr);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body onload=\"initImgId()\">\r\n");
      out.write("\t<div class=\"c1\" id=\"msgMain_01\">\r\n");
      out.write("\t\t<hr style=\"width: 1000px; height: 1px; background-color: grey; border:0px\">\r\n");
      out.write("\t\t<div class=\"imgd\">\r\n");
      out.write("\t\t\t<img id=\"img_01\" alt=\"headImg\" width=\"100px\" height=\"100px\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span class=\"name\" id=\"name_01\"></span>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<span class=\"time\" id=\"floor_01\" ></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<div class=\"option\">\r\n");
      out.write("\t\t\t\t<ul style=\"list-style-type: none; \">\r\n");
      out.write("\t\t\t\t\t<li  onmouseleave=\"testHide(ls.$('hide_01'))\" onmouseover=\"testShow(ls.$('hide_01'))\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" >▼</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"hide\" id=\"hide_01\" style=\"display: none;text-align:center;list-style-type: none; margin-left: -60px;border: 1px solid;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a  onclick=\"return deltInfo('msgMain_01')\">删除</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a  onclick=\"return changeContent('content_01', 'editeDiv_01', 'editContent_01')\">更改</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"edit\" id=\"editeDiv_01\">\r\n");
      out.write("\t\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<textarea id=\"editContent_01\" name=\"\" rows=\"10\" cols=\"75\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"确认\"  onclick=\"return submitValue('content_01', 'editeDiv_01', 'editContent_01')\" />\r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" value=\"取消\" />\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"innerContern\" id=\"content_01\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p class=\"time\" id=\"time_01\"></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
